name: Build cefbrowser base

env:
  TAG: "1.0"

on:
  workflow_dispatch

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build images
        run: |
          cd cefbrowser-base-docker 
          
          docker build -t zabrimus/cefbrowser-base:${TAG}-amd64 --build-arg ARCH=amd64/ . 
          docker push ghcr.io/zabrimus/cefbrowser-base:${TAG}-amd64
          
          docker build -t zabrimus/cefbrowser-base:${TAG}-arm32v7 --build-arg ARCH=arm32v7/ .
          docker push ghcr.io/zabrimus/cefbrowser-base:${TAG}-arm32v7
          
          docker build -t zabrimus/cefbrowser-base:${TAG}-arm64v8 --build-arg ARCH=arm64v8/ .
          docker push ghcr.io/zabrimus/cefbrowser-base:${TAG}-arm64v8
          
          docker manifest create zabrimus/cefbrowser-base:${TAG} \
              --amend zabrimus/cefbrowser-base:${TAG}-amd64 \
              --amend zabrimus/cefbrowser-base:${TAG}-arm32v7 \
              --amend zabrimus/cefbrowser-base:${TAG}-arm64v8 

          docker manifest push ghcr.io/zabrimus/cefbrowser-base:${TAG}