name: CoreELEC/LibreELEC Docker Build Images

on:
  workflow_dispatch

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout CoreELEC
        uses: actions/checkout@v5
        with:
          repository: CoreELEC/CoreELEC
          path: coreelec

      - name: Patch Docker files
        run: |
          cd coreelec 
          pwd
          echo "......"
          ls -la ..
          echo "."
          ls -la
          patch -p1 < ../docker-patches/add-wget.patch

      - name: CoreELEC/LibreELEC.tv Jammy
        uses: docker/build-push-action@v6
        with:
          context: ./coreelec/tools/docker/jammy
          push: true
          tags: ghcr.io/zabrimus/ce-le-builder/22.04:latest

      - name: CoreELEC/LibreELEC.tv Noble
        uses: docker/build-push-action@v6
        with:
          context: ./coreelec/tools/docker/noble
          push: true
          tags: ghcr.io/zabrimus/ce-le-builder/24.04:latest

      - name: CoreELEC/LibreELEC.tv Plucky
        uses: docker/build-push-action@v6
        with:
          context: ./coreelec/tools/docker/plucky
          push: true
          tags: ghcr.io/zabrimus/ce-le-builder/25.04:latest

